### ISSUE TITLE
values of "Channel B" are not getting saved on the "ADSR applet" of hemispheres

### ISSUE THREAD

**Issue by pssssssst** [djphazer/O_C-Phazerville#108]
When i save a hemisphere state that is using the ADSR applet, the values of Channel B of the applet are not getting saved correctly.
After loading the save state, the changes made to Channel b are gone.

**Comment by djphazer** [comment]
My apologies! This was just an oversight - there is enough space to store both envelopes, but it only saves one. I'll push a fix for this soon. 

I've been meaning to give the ADSR applet more attention; there's plenty of room for improvement...

**Comment by pssssssst** [comment]
No worries. Thanks for your work. I'm really appreciating my o_C with phazerville. For a small Rack like mine this is so nice.

**Comment by djphazer** [comment]
Fixed in v1.8.3!
