### ISSUE TITLE
Bug with helper screen in hemisphere

### ISSUE THREAD

**Issue by nervousapps** [djphazer/O_C-Phazerville#12]
When in an applet helper, the encoder is not locked and it is going in a strange behavior, applets ate below the helper screen. I don't know if it is a bug related to this project or from hemisphere suite directly.

Step to reproduce (see video attached):
- Push the button to enter applet helper screen
- Turn the encoder
- Return to the applet screen

https://github.com/djphazer/O_C-BenisphereSuite/assets/21999923/813d6c02-f285-468a-8110-b943cfd7a900

**Comment by djphazer** [comment]
Oh no! That's definitely a bug I introduced, thank you for pointing it out!

**Comment by djphazer** [comment]
Fixed in commit https://github.com/djphazer/O_C-BenisphereSuite/commit/754c0bff540b92e30c82b5488d2f36eecb393717
It will be in the next build! 😃
