### ISSUE TITLE
Knob directions reversed in flipped main build?

### ISSUE THREAD

**Issue by discohead** [djphazer/O_C-Phazerville#15]
Just tried out the flipped build for the first time and I guess the knobs are not "flipped", because turning right now moves left/moves up/decreases and turning left moves rights/moves down/increases. Wasn't sure if this is a known issue or not, if so, feel free to close. I'm running v1.6.1

**Comment by djphazer** [comment]
I actually considered this a standard calibration difference before now... you can adjust the encoders' direction on the Calibration screens in the "Setup / About" app. (press either Up/Down buttons to cycle through)

But I could probably invert that setting as well for the flipped build and save us all the trouble 😉 Thanks for the nudge

**Comment by discohead** [comment]
Got it. Thanks for the tip. Yea, making `R reversed` the default setting for flipped builds seems like a good idea..

**Comment by djphazer** [comment]
I pushed a fix for this here: https://github.com/djphazer/O_C-BenisphereSuite/commit/cb06389fe4106c3e5bbf7e150fe334ecfa4f1de9
The next release that includes it will require you to adjust the calibration once, but never again ;)
