### ISSUE TITLE
Cannot get to clock setup screen in 1.6.4

### ISSUE THREAD

**Issue by xmacex** [djphazer/O_C-Phazerville#25]
Hiya, with the new [1.6.4 release](https://github.com/djphazer/O_C-BenisphereSuite/releases/tag/PSv1.6.4) yesterday, I can no longer access the clock setup with the <kbd>▴</kbd>+<kbd>▾</kbd> gesture. Instead, it gets me to the new screen saver screen. It worked earlier today before I updated.

Looking at commit messages, #389790d has a hint maybe... can I help debugging/testing? Or did something happen to my fingers?

O_c is so cool! Thanks for w/forking on it 😎

**Comment by djphazer** [comment]
Lol oh dammit, maybe we've taken a step backward. You've correctly pinpointed the commit in question. I'll have to revisit it...

I think the edge case was happening when you hit both buttons at exactly the same time - the first one is processed and the second (button down) is immediately ignored. When you release, the first is ignored but the second (button release) still fires, thus cancelling the screen.

With the old behavior restored, the trick is just pressing both buttons within a 60ms window.

**Comment by xmacex** [comment]
The gesture I embodied with 1.6.3. (which is when I got onboard this Eurorack madness, with O_c being my second module and an obvious choice, not least because of this firmware) was to

1. press <kbd>▴</kbd>
2. press <kbd>▾</kbd>
3. (clock setup appears)
4. release <kbd>▴</kbd>
5. release <kbd>▾</kbd>

...a kind of a galloping 🏇 gesture. I admit I do it kind of quick, like one sweep left-to-right and it worked very well! It seems with 1.6.4. I fail to get into the clock setup because screensaver activates if I keep the <kbd>▴</kbd> pressed any longer. Lol I feel so clumsy. I'll work on my finger technique, and report back how it goes.

**Comment by djphazer** [comment]
Don't feel like it's your fault! If something doesn't work intuitively, I would never blame the user. I like to use a similar "galloping" gesture as well ;)

I'm working on a quick bugfix release, and I actually found a better solution for this already: https://github.com/djphazer/O_C-BenisphereSuite/commit/4d212cf8d68c105cc848afb0c89b4a6e99e80caa

**Comment by djphazer** [comment]
Just published v1.6.5 with the fix! Feel free to reopen if you still have trouble.

**Comment by xmacex** [comment]
Just galloping :horse: here to inform that with 1.6.5. it works as it did in 1.6.3. Back at 145 bpm, the true and correct tempo haha :)

Cheers!
