### ISSUE TITLE
Could Scenes be 3 channels with 4th channel sending combined gate?

### ISSUE THREAD

**Issue by jococo** [djphazer/O_C-Phazerville#31]
Scenes, like Traffic, can be used to create drums patterns, for example feeding several Plaits voltages to make individual percussion sounds. In this situation the various gates need to be summed to create gate that triggers the Plaits envelope. This takes a fair bit of patching to achieve outside O_c but could be easily achieved by dedicating the last channel as the combined gate output. Traffic has this useful feature too. What do you think? Could Scenes be customised to achieve this?

**Comment by djphazer** [comment]
Ah yes, I did consider this! When I get back to it, I think I'll probably make Left Encoder Long-press toggle output D to **Trig Sum** mode

**Comment by jococo** [comment]
Awesome! Making it optional is an even better idea.

**Comment by djphazer** [comment]
Implemented in v1.6.6

**Comment by jococo** [comment]
Wow, that was quick work! Will check it out tonight after work.

**Comment by jococo** [comment]
Works perfectly, thanks @djphazer !
