### ISSUE TITLE
Thank you for taking O_c forward

### ISSUE THREAD

**Issue by xmacex** [djphazer/O_C-Phazerville#33]
The original Ornament and Crime was already a very interesting, and inspiring /inspired, and importantly affordable open source Eurorack module. The Hemisphere took it to a new direction and the modularity idea there was so good.

Your Phazerville firmware carries forward (via Benisphere, respect there too) and adds onto the legacy of this legendary module.

![nonsithering.gif](https://github.com/djphazer/O_C-BenisphereSuite/assets/879300/ab217e7f-162f-419c-83bc-a671218247ba)

I am convinced I speak for many O_c users, no matter which firmware they use, in the following: thank you for what you have done to maintain and develop Ornament and Crime.

Have a nice day 🕊️

[To be closed after you've read this]

**Comment by djphazer** [comment]
Thank you so much for your kind words! This has been a very rewarding hyperfixation - moreso than actually producing music. People tend to be far more interested in music tools than random beats some guy made.

Software Development is my art 🎨

Stay tuned - the best is yet to come!

**Comment by xmacex** [comment]
Software development is a legit artform! Cheers :)
