### ISSUE TITLE
branches probability

### ISSUE THREAD

**Issue by mebitek** [djphazer/O_C-Phazerville#36]
Hi, when you cv branches prob abilty the display doesn't show the current value but remains at the one you input via encoder

**Comment by djphazer** [comment]
Good call! I'll tweak that for better visual feedback.

**Comment by djphazer** [comment]
Implemented in v1.6.999

The CV input scaling is somewhat different now - before it was going well out of range (143% for example) but you couldn't see it. After rework, +6V will yield +100%; -3V yields -50%; and you can see it.

**Comment by mebitek** [comment]
just tested the 999 phazerville release and I cannot see the probability changes when I modulate it

**Comment by djphazer** [comment]
With and without a voltage applied to CV1, I see this:
![20231224_022950-COLLAGE.jpg](https://github.com/djphazer/O_C-BenisphereSuite/assets/109086194/f0958f80-e317-4a53-ae2f-fc491e337d83)

We're talking about the same applet, Brancher?

**Comment by mebitek** [comment]
sorry my fault, wrong input!
