### ISSUE TITLE
voltage drop when screensaver appears

### ISSUE THREAD

**Issue by sebpmtl** [djphazer/O_C-Phazerville#43]
Happened when I was using SequenceX, I noticed a slight voltage drop when the screensaver appeared. I could hear it on the sequence playing.  today, I'll re-test with my oscilloscope to see what's going on, to make sure it's not my oscillator.

**Comment by djphazer** [comment]
VOR? Auto-save enabled?
Auto-save will cause a slight hiccup...

If it's really a voltage drop from extra processing, try the `[blank]` screensaver.

**Comment by sebpmtl** [comment]
also, saving doesn't work anymore. I save as I always saved and it starts on DualTM and EuclidX on startup.

**Comment by sebpmtl** [comment]
I did't see the extra settings. Sorry. I think it was my quantizer.

**Comment by djphazer** [comment]
Hopefully this was just a false alarm? It seems like a slight possibility on VOR hardware, but I wasn't able to reproduce. Feel free to reopen if you're able to nail it down.
