### ISSUE TITLE
Compiling and Flashing multiple times

### ISSUE THREAD

**Issue by TricksterSam** [djphazer/O_C-Phazerville#46]
I'm using PlatformIO in Visual Studio. When I compile the code, it looks to me like the compile process is happening 3 or 4 times. If I flash the Ornament and Crime, it also seems to repeat the flash 3 or 4 times. Any hint as to why it might be doing this?

**Comment by djphazer** [comment]
If you're using the Default build target, it's probably building 4 or 5 targets in a row, which is useful for continuous integration and preparing releases.

You'll want to pick a specific build target config like `pewpewpew` or `main`. Refer to the `platformio.ini` file

**Comment by TricksterSam** [comment]
Perfect. Thanks!
