### ISSUE TITLE
SBD_MIDI start error; cant compile

### ISSUE THREAD

**Issue by synthi** [djphazer/O_C-Phazerville#5]
Trying to complile for my buchla 2OC, using Arduino IDE 1-8-1 + teensyduino.
I keep getting the following error:

C:\Users\Usuario\Documents\Arduino\O_C-BenisphereSuite-cal8app-beta\software\o_c_REV\HEM_ClockSetup.ino: In member function 'virtual void ClockSetup::Controller()':

HEM_ClockSetup:50: error: 'class usb_midi_class' has no member named 'Start'
             usbMIDI.sendRealTime(usbMIDI.Start);

                                        

HEM_ClockSetup:54: error: 'class usb_midi_class' has no member named 'Stop'
             usbMIDI.sendRealTime(usbMIDI.Stop);

                                          

HEM_ClockSetup:56: error: 'class usb_midi_class' has no member named 'Clock'
         if (clock_m->IsRunning() && clock_m->MIDITock()) usbMIDI.sendRealTime(usbMIDI.Clock);

                                                                                      

'class usb_midi_class' has no member named 'Start'

**Comment by djphazer** [comment]
Older versions of the teensyduino framework were missing definitions for `usbMIDI.Start`, `usbMIDI.Stop` and `usbMIDI.Clock`. I've abandoned support for the older Arduino IDE in favor of Platform IO, but you might still succeed if you revert the relevant lines from this commit: https://github.com/djphazer/O_C-BenisphereSuite/commit/f741b4d58f8735c20a158cedecaa89ee67214f9c

I honestly should have left it alone for better compatibility, but this serves as a gentle suggestion to upgrade your toolchain!

**Comment by synthi** [comment]
Thanks! will try to revert vhanges... The problem seem to be that the Buchla builds only work when compiled with theese older tools... when compiling with updated versions the triggers don´t work... there is sone discussion here: https://modwiggler.com/forum/viewtopic.php?t=229917&start=25

**Comment by synthi** [comment]
I managed to download platformIO and complile the firmware! And seem to be working for Buchla! Thanks!

**Comment by djphazer** [comment]
Great news! This affirms that the newer build toolchain is indeed stable and robust. 🦾

Perhaps let the forum folks know of your success. Closing this issue as complete.
