### ISSUE TITLE
Carpeggio doesn't clock

### ISSUE THREAD

**Issue by yratof** [djphazer/O_C-Phazerville#50]
![image](https://github.com/djphazer/O_C-Phazerville/assets/1001935/38d16b2c-682f-4bda-b430-60a36a6bc771)

this has been an issue for a while, but was going somewhat under the radar since Shredder replaced this, but it's worth mentioning, internal clocking doesn't trigger anything either

**Comment by djphazer** [comment]
Hardware-related glitch if powering the module via USB only (unsupported) - your inputs won't work correctly. Highly recommend cutting the VUSB power trace on the Teensy, so you can safely connect USB while using proper case power.

For the record, this may also happen if your input calibration is way off - https://www.youtube.com/shorts/AIadpDclP7M
