### ISSUE TITLE
Bug - Clock Skipper CV

### ISSUE THREAD

**Issue by jamesdmorgan** [djphazer/O_C-Phazerville#68]
Noticed a problem with the cv input for Clock Skipper.

The documentation says it modulates the probability.

I found that it didn't do anything. I validated the CV input on other hemisphere apps and it works fine.

Unless i'm doing something completely wrong I think it doesn't work.

I'm on v1.7 (custom build via the GHA)

Cheers

James

**Comment by djphazer** [comment]
The input modulation probably works, but it looks like the UI just doesn't reflect the modulated value. I'll definitely fix that! Thanks for reporting this!

**Comment by jamesdmorgan** [comment]
Nice one. I ran it through Mordax data and didn’t see a change in gates but
I may have given up

It definitely changes when I messed with the encoder.

Btw your additions have really enhanced O_c massively

Nice work

**Comment by djphazer** [comment]
Fixed in v1.7.1
