### ISSUE TITLE
Applet Suggestion: Nibbler-esque binary adder

### ISSUE THREAD

**Issue by SavageMessiah** [djphazer/O_C-Phazerville#69]
A fun thing you can do with the Schlappi nibbler is to generate gate patterns by using the adder. It's really simple and seems like it could be a fun applet for hemispheres. The user would choose a value to add/subtract with each clock, the number of bits in the adder, and choose two bits to route to the outputs. If we're feeling saucy you could also choose to output a stepped voltage, too. Given what a lot of the other applets are like, this seems like it would be pretty easy to implement.

So something like this:

TR1: clock TR2: reset
CV1: offset to add/subtract value CV2: offset to bit length ?
OUT1: configurable OUT2: configurable

The output choices would be a bit number or stepped voltage.

A fancier version of the applet would let you choose from pairs of bits and a boolean function on them for each output but I'm not sure if that's worth the additional UI complexity. It would still be less complex than DualTM so maybe that's fine?

**Comment by zerbian** [comment]
Looks like an interesting idea, I might look into it and create a simple demo.

**Comment by zerbian** [comment]
I did get some time to spend and worked on this little applet ("Cumulus"):
![photo_5296704522019789208_y](https://github.com/djphazer/O_C-Phazerville/assets/38952981/a495eb99-21ee-4b6c-a8ca-a9b88ff93acc)

You can set the operation mode (ADD, SUB, MUL, XOR with ROTL) and assign the different bits of the accumulator register (Z) to the outputs. The constant value (k) can either be set by the encoder or the CV1 (this overwrites the encoder value).

It tested it and it gave some interesting rhythms, especially when modulating the constant. I might look into more interesting operations and maybe implement some stepped voltage output as well.

https://github.com/zerbian/O_C-Phazerville/tree/app-accumulator

**Comment by ph1-xyz** [comment]
> I did get some time to spend and worked on this little applet ("Cumulus"): 

What does your clock icon do? If it may add to your app appearance, I dabbled a few minutes with the hex editor :-D

![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/e77e42fb-44a9-4d84-87cc-8b0480711290)
{ 0x02, 0x11, 0x21, 0x22, 0x44, 0x12, 0x42, 0x84 }

![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/7fb6a494-3acd-4623-8beb-9e5dfce201b2)
{ 0x49, 0x26, 0x08, 0x54, 0x44, 0x24, 0x8a, 0x01 }

**Comment by zerbian** [comment]
The clock icon is just there to represent the current operation (as label), but I probably can get rid of it.
Are your icons supposed to be clouds? I cannot not really recognize their shape.

**Comment by djphazer** [comment]
Haha they do seem like vague cloud-esque textures... do they tile? Could probably squeeze them into the header 😜

Happy to see this applet though, just in time to slip it into the next beta build for testing!

**Comment by zerbian** [comment]
Sounds like a plan! I am going to fix some stuff I noticed, implement some parameter saving and then prepare a pull request.

**Comment by ph1-xyz** [comment]
> Haha they do seem like vague cloud-esque textures... do they tile? Could probably squeeze them into the header 😜

These currently not much, 

![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/e77e42fb-44a9-4d84-87cc-8b0480711290) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/e77e42fb-44a9-4d84-87cc-8b0480711290) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/7fb6a494-3acd-4623-8beb-9e5dfce201b2) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/7fb6a494-3acd-4623-8beb-9e5dfce201b2) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/e77e42fb-44a9-4d84-87cc-8b0480711290)

but if @zerbian might like the idea I could work on them!

Maybe we could bind the representation to some parameter or behaviour of the app!

**Comment by ph1-xyz** [comment]
Something like...

{ 0x20, 0xa4, 0x12, 0x12, 0x89, 0x61, 0x12, 0x10 }
{ 0x40, 0x10, 0x88, 0x84, 0x44, 0x48, 0x24, 0x10 }
{ 0x10, 0x28, 0x48, 0x90, 0xa0, 0x20, 0x58, 0x04 }

![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/6034890d-a659-4519-baef-44fb3952de95) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/08dc9b86-01fd-463d-a6c9-ccbab56fdacf) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/0e80323a-9094-4b99-9bc1-b8acf8b8bea1) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/6034890d-a659-4519-baef-44fb3952de95) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/08dc9b86-01fd-463d-a6c9-ccbab56fdacf) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/0e80323a-9094-4b99-9bc1-b8acf8b8bea1) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/6034890d-a659-4519-baef-44fb3952de95) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/08dc9b86-01fd-463d-a6c9-ccbab56fdacf) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/0e80323a-9094-4b99-9bc1-b8acf8b8bea1) 

{ 0x08, 0x24, 0x12, 0x12, 0x89, 0x49, 0x32, 0x44 }
{ 0x48, 0x10, 0x88, 0x84, 0x44, 0x48, 0x24, 0x18 }
{ 0x10, 0x28, 0x48, 0x90, 0xa0, 0x40, 0x30, 0x08 }

![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/741b1dd3-8bfd-4fbf-aa9e-b5e032adb798) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/b4fd988c-2158-4713-88c8-ed86b752f8e7) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/895ed61f-8cd6-4f79-a847-54a3fdc30357) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/b4fd988c-2158-4713-88c8-ed86b752f8e7) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/741b1dd3-8bfd-4fbf-aa9e-b5e032adb798 )![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/741b1dd3-8bfd-4fbf-aa9e-b5e032adb798) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/b4fd988c-2158-4713-88c8-ed86b752f8e7) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/895ed61f-8cd6-4f79-a847-54a3fdc30357)

or, another idea could maybe to cycle through them as an animation? Maybe.... As a Shift Register :-DD

**Comment by zerbian** [comment]
Originally I choose the clock icon because I dint find any icon that corresponds to "Operation" or "Mode", so I choose the clock as the instruction only happens on the clock pulse. If you have a better idea, feel free to design something @ph1-xyz

**Comment by ph1-xyz** [comment]
I may be understanding now, it regarded the operation at the right and not something regarding clocking...

An idea that comes to my mind is that of the [beaker](https://en.wikipedia.org/wiki/Beaker_(laboratory_equipment)), which, boiling will produce more or less (disordered) bubbles.

So, the icon could represent the bit-"entropy" produced from the app :-)

![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/62ff8019-bf0b-4e25-be23-c0fbc2613520) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/5855c6be-943e-4989-96aa-87c1d45349b6) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/e7a1e496-0b45-44be-8228-41733586a69e)

{ 0x70, 0x88, 0x07, 0x20, 0x00, 0x17, 0x88, 0x70 }
{ 0x70, 0x88, 0x27, 0x00, 0x90, 0x07, 0x88, 0x70 }  
{ 0x70, 0x88, 0x27, 0x40, 0x90, 0x27, 0x88, 0x70 }

**Comment by ph1-xyz** [comment]
May we even try different shape per operation? :-D

![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/203eb5e4-bfd2-4597-a30f-ade7c8cec3ac) ![image](https://github.com/djphazer/O_C-Phazerville/assets/6156113/346f5705-36f4-4951-a000-18deb3e4202c)

{ 0xc0, 0x20, 0x9c, 0x00, 0x40, 0x9c, 0x20, 0xc0 }
{ 0x02, 0xfe, 0x00, 0x48, 0x80, 0x10, 0x00, 0xfe }

**Comment by zerbian** [comment]
see https://github.com/djphazer/O_C-Phazerville/pull/72

**Comment by djphazer** [comment]
The new Cumulus applet is included in v1.7.1

Thank you @zerbian !!

(and thanks always to @ph1-xyz for the icons/animation ideas - I might have to save some of these for future use! ;)
