### ISSUE TITLE
Glitch in quadraturia mode (1.7 and 1.Z)

### ISSUE THREAD

**Issue by Burdienco** [djphazer/O_C-Phazerville#71]
Did anyone had some dlitches in quadraturia mode. In my case it just once in a few seconds jumps to some randome value for just a few frames in video terms, so much less than a second. To tes it I put ampletude of LFO to 0 so on the scope it shows plane horizontal line, and once in 5 or 6 seconds it jumps up and it is displayed on the screen as well. It would be clear if I could show video or picture, but I already installed v 1.69, it works fine.

**Comment by djphazer** [comment]
Can you clarify what hardware you're using?

By the way, we don't talk about v1.Z - it's not safe there. Too many Zaps. 😬

**Comment by djphazer** [comment]
I'm able to reproduce on Plum OCP X with v1.7. Seems like the "Output range" (attenuation) parameter is broken? I've neglected to test Quadraturia very much, so maybe I broke it recently. I'll have to dig deeper...

**Comment by Burdienco** [comment]
![photo_2024-05-01_15-47-38](https://github.com/djphazer/O_C-Phazerville/assets/145282078/f3c1314d-d695-46d1-8441-b2a2bf72bd0e)
![photo_2024-05-01_15-47-56](https://github.com/djphazer/O_C-Phazerville/assets/145282078/b585b8fe-2dbd-4430-96af-719329231541)
![photo_2024-05-01_15-50-45](https://github.com/djphazer/O_C-Phazerville/assets/145282078/0d6f0870-31f6-476b-b80a-146d0ff8e806)

Hardware is like on picture, and yeah, its about output range, I couldn't install that 1.7 to make a picture, but I made some drowinds, it roughly represent how it looks on the screen. It's well seen when I put output range at 1, and as it is on the picture, once in a few seconds it jumps up. Another drawing is when it sapose to be a sine wave with normal averege output

**Comment by djphazer** [comment]
Bug squashed, I think (i'm very tired) - https://github.com/djphazer/O_C-Phazerville/commit/e0a4006fb53573080ab81a9f35ff905f45f3b203

I still don't quite understand it... What exactly happens when you access an array at index -1? "Undefined behavior"? How did it work before? Why did it break? Spooky stuff...

Anyway, the fix is pushed to the main `phazerville` branch, so a fresh Custom Build will include it. Let me know if it clears things up!

**Comment by djphazer** [comment]
Fixed in v1.7.1
