### ISSUE TITLE
Feature Idea: Subharmonicon

### ISSUE THREAD

**Issue by yratof** [djphazer/O_C-Phazerville#8]
Been playing around with the code to try to make a subharmonicon applet, but i'm not experienced enough to get it running

I think it would be two apps

First app would:

1) Take in a frequency into the CV1
2) Spit out 2 harmonic frequencies based on user selected division on out1/out2

Second app would take in a clock and advance a sequence, but you would set how long each of 4+ gates would stay open for.
1) Set clock division for each step
2) Send out trigger on out3 for each step, send passthrough clock on out4 

Here is how I'm picturing the UI:

![image](https://user-images.githubusercontent.com/1001935/228502194-c273a48c-3f61-41e8-9855-cdc70a33c3ff.png)

Or if it's possible to double it up, have the polyrhythm have two sequences

![image](https://user-images.githubusercontent.com/1001935/228504484-9c0eb681-4ddb-446f-a460-ccf9d7a92521.png)

In which the Out4 would do the second channel of rests

Reference to the subharmonicon's idea:

![image](https://user-images.githubusercontent.com/1001935/228768752-7828d737-3081-49f9-aca6-d7989d82ac4b.png)

2 sequencers, 1 polyrhythm that can be applied to each step of the sequence or not

How mad am I to suggest this?

**Comment by djphazer** [comment]
Very cool idea! The sequencer part sounds like something I would immediately enjoy...

To be clear, would the harmonic divider part deal with audio rate? or pitch CV?

**Comment by yratof** [comment]
I'm assuming it would work like a quantiser, but transposing it by the subharmonic division.

**Comment by yratof** [comment]
On this - do we have any apps that can take a clock and click divide it, but each divider waits for previous divisions trigger before dividing

**Comment by djphazer** [comment]
There's the standard **[Clock Div](https://github.com/Chysn/O_C-HemisphereSuite/wiki/Clock-Divider-Multiplier)** applet.
There's also Beni's stochastic [**ProbDiv**](https://github.com/benirose/O_C-BenisphereSuite/wiki/ProbDiv) applet.

Nothing quite like the Subharmonicon sequencer tho, this is a unique applet idea - a deliberate clock division sequencer.
I also need to figure out the math involved to convert a harmonic ratio into a V/Oct offset for the subharmonizer pitch applet.

**Comment by yratof** [comment]
It's going to be a great tool

**Comment by vestedaf** [comment]
This is an awesome idea! I need a second o_C so badly...

**Comment by yratof** [comment]
Did this idea ever make it past this suggestion?

**Comment by djphazer** [comment]
Unfortunately not yet...

**Comment by djphazer** [comment]
Sorry for sleeping on this one... after some discussion on Discord about using the O_C for (sub)harmonic series quantization, I'm now aware of some scales already present in the firmware that might help realize this app idea. I may try to tackle it after the big weekend...

**Comment by yratof** [comment]
Sounds like a fantastic halloween plan :D

**Comment by yratof** [comment]
Ayup - How are plans going for anything such as the above ;)

**Comment by yratof** [comment]
Closing this issue as we now have the [Polydiv](https://github.com/djphazer/O_C-Phazerville/blob/PSv1.7-beta1/software/src/applets/PolyDiv.h) & [DivSeq](https://github.com/djphazer/O_C-Phazerville/blob/PSv1.7-beta1/software/src/applets/EbbAndLfo.h) in 1.7.beta1 resolving the feature request
