### ISSUE TITLE
EnsOsc freezes when Enigma Jr is also on the applet

### ISSUE THREAD

**Issue by laineb89** [djphazer/O_C-Phazerville#92]
Using build o_C-phazerville-v1.7.1_phz-2b02dc39, Enigma jr on Left applet and EnsOsc on right. O_c Becomes Unresponsive

**Comment by djphazer** [comment]
Duplicate of #80 - it freezes when you try to move from EnigmaJr to another copy of EnsOscKey.

Suffice to say, I'll be disabling this applet until it is rewritten with fewer floating point calculations.
